import { Icon } from '@equinor/eds-core-react';
import {
    add,
    arrow_back,
    arrow_drop_down,
    arrow_drop_right,
    arrow_forward,
    assignment_turned_in,
    attachment,
    bookmark_filled,
    bookmark_outlined,
    border_color,
    camera_add_photo,
    check,
    check_circle_outlined,
    checkbox,
    checkbox_outline,
    chevron_down,
    chevron_right,
    chevron_up,
    close,
    cloud_download,
    delete_to_trash,
    download,
    error_filled,
    error_outlined,
    external_link,
    file,
    hourglass_empty,
    info_circle,
    launch,
    link,
    list,
    menu,
    paste,
    radio_button_selected,
    radio_button_unselected,
    remove,
    search,
    stop,
    swap_horizontal,
    tag,
    thumbs_up,
    tune,
    view_list,
    warning_filled,
    warning_outlined,
    wifi_off,
} from '@equinor/eds-icons';

Icon.add({
    camera_add_photo,
    tag,
    attachment,
    external_link,
    menu,
    stop,
    tune,
    file,
    link,
    delete_to_trash,
    cloud_download,
    chevron_right,
    chevron_down,
    chevron_up,
    arrow_drop_down,
    error_outlined,
    close,
    bookmark_outlined,
    bookmark_filled,
    list,
    assignment_turned_in,
    border_color,
    paste,
    view_list,
    remove,
    check_circle_outlined,
    arrow_back,
    arrow_forward,
    search,
    warning_outlined,
    warning_filled,
    radio_button_selected,
    radio_button_unselected,
    swap_horizontal,
    arrow_drop_right,
    info_circle,
    checkbox,
    checkbox_outline,
    thumbs_up,
    error_filled,
    hourglass_empty,
    check,
    add,
    launch,
    download,
    wifi_off,
});

type IconProps = {
    name: string;
    title?: string;
    color?: string;
    size?: 16 | 24 | 32 | 40 | 48 | undefined;
    quantity?: number;
    alt?: string;
};

const EdsIcon = ({ name, title, color, size }: IconProps): JSX.Element => {
    return <Icon name={name} title={title} color={color} size={size} />;
};

export default EdsIcon;
